services:
  talko:
    container_name: talko-service
    build: .
    restart: on-failure
    ports:
      - "8003:8003"
    volumes:
      - .:/talko-service
    env_file:
      - .env
    depends_on:
      - talko-mongodb
      - redis
    networks:
      - talko_network
    environment:
      - PYTHONPATH=/talko-service

  talko-mongodb:
    container_name: talko-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    env_file:
      - .env
    volumes:
      - mongodbdata:/var/lib/mongodb/data
    networks:
      - talko_network
  redis:
    container_name: talko-redis
    image: redis
    ports:
      - 6381:6379
    volumes:
      - redisdata:/data
    networks:
      - talko_network

  celery-worker:
    build: .
    container_name: talko-worker
    command: poetry run celery -A src.talko_celery.celery_app.celery worker --loglevel=info --concurrency=6 -Q default_queue,call_operation_queue,call_assets_queue,did_management_queue,call_management_queue,missed_callback_queue,webhook_delivery_queue
    volumes:
      - .:/talko-service
    networks:
      - talko_network

  celery-beat:
    build: .
    container_name: talko-beat
    command: poetry run celery -A src.talko_celery.celery_app.celery beat --loglevel=info
    volumes:
      - .:/talko-service
    networks:
      - talko_network

volumes:
  mongodbdata:
  redisdata:

networks:
  talko_network:
    driver: bridge
