# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api_key_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api_key_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pi_key_service.proto\x12\x06\x61pikey\"$\n\x15ValidateApiKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"X\n\x16ValidateApiKeyResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x12\n\npartner_id\x18\x03 \x01(\x03\x12\x11\n\tis_active\x18\x04 \x01(\x08\x32`\n\rApiKeyService\x12O\n\x0eValidateApiKey\x12\x1d.apikey.ValidateApiKeyRequest\x1a\x1e.apikey.ValidateApiKeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_key_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEAPIKEYREQUEST']._serialized_start=33
  _globals['_VALIDATEAPIKEYREQUEST']._serialized_end=69
  _globals['_VALIDATEAPIKEYRESPONSE']._serialized_start=71
  _globals['_VALIDATEAPIKEYRESPONSE']._serialized_end=159
  _globals['_APIKEYSERVICE']._serialized_start=161
  _globals['_APIKEYSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
