# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import api_key_service_pb2 as api__key__service__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in api_key_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ApiKeyServiceStub(object):
    """API Key component service"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateApiKey = channel.unary_unary(
            "/apikey.ApiKeyService/ValidateApiKey",
            request_serializer=api__key__service__pb2.ValidateApiKeyRequest.SerializeToString,
            response_deserializer=api__key__service__pb2.ValidateApiKeyResponse.FromString,
            _registered_method=True,
        )


class ApiKeyServiceServicer(object):
    """API Key component service"""

    def ValidateApiKey(self, request, context):
        """RPC to validate an API key and retrieve its details"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ApiKeyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ValidateApiKey": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateApiKey,
            request_deserializer=api__key__service__pb2.ValidateApiKeyRequest.FromString,
            response_serializer=api__key__service__pb2.ValidateApiKeyResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "apikey.ApiKeyService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("apikey.ApiKeyService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ApiKeyService(object):
    """API Key component service"""

    @staticmethod
    def ValidateApiKey(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/apikey.ApiKeyService/ValidateApiKey",
            api__key__service__pb2.ValidateApiKeyRequest.SerializeToString,
            api__key__service__pb2.ValidateApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
