# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """The authentication service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateToken = channel.unary_unary(
                '/auth.AuthService/ValidateToken',
                request_serializer=auth__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.GetUserChildHierarchy = channel.unary_unary(
                '/auth.AuthService/GetUserChildHierarchy',
                request_serializer=auth__pb2.GetUserChildHierarchyRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserChildHierarchyResponse.FromString,
                _registered_method=True)
        self.GetUserChildDetails = channel.unary_unary(
                '/auth.AuthService/GetUserChildDetails',
                request_serializer=auth__pb2.GetUserChildDetailsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserChildDetailsResponse.FromString,
                _registered_method=True)
        self.GetUserDetails = channel.unary_unary(
                '/auth.AuthService/GetUserDetails',
                request_serializer=auth__pb2.GetUserDetailsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserDetailsResponse.FromString,
                _registered_method=True)
        self.GetUserPermissions = channel.unary_unary(
                '/auth.AuthService/GetUserPermissions',
                request_serializer=auth__pb2.GetUserPermissionsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserPermissionsResponse.FromString,
                _registered_method=True)
        self.GetUserRole = channel.unary_unary(
                '/auth.AuthService/GetUserRole',
                request_serializer=auth__pb2.GetUserRoleRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserRoleResponse.FromString,
                _registered_method=True)
        self.GetServiceBoardUsersDetails = channel.unary_unary(
                '/auth.AuthService/GetServiceBoardUsersDetails',
                request_serializer=auth__pb2.GetUsersDetailsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetServiceBoardUserDetailsResponse.FromString,
                _registered_method=True)
        self.GetPartnerApiKey = channel.unary_unary(
                '/auth.AuthService/GetPartnerApiKey',
                request_serializer=auth__pb2.GetPartnerApiKeyRequest.SerializeToString,
                response_deserializer=auth__pb2.GetPartnerApiKeyResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """The authentication service definition.
    """

    def ValidateToken(self, request, context):
        """RPC to validate a token and return user information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserChildHierarchy(self, request, context):
        """RPC to get the list of child users for a given user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserChildDetails(self, request, context):
        """RPC to get the list of child users for a given user along with their directory information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserDetails(self, request, context):
        """add GRPC method to get CurrentUserDetails.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserPermissions(self, request, context):
        """RPC to get list of permission for given user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserRole(self, request, context):
        """RPC to get User role
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceBoardUsersDetails(self, request, context):
        """RPC to get service board user details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartnerApiKey(self, request, context):
        """RPC to get Partner API KEY
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=auth__pb2.ValidateTokenRequest.FromString,
                    response_serializer=auth__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'GetUserChildHierarchy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserChildHierarchy,
                    request_deserializer=auth__pb2.GetUserChildHierarchyRequest.FromString,
                    response_serializer=auth__pb2.GetUserChildHierarchyResponse.SerializeToString,
            ),
            'GetUserChildDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserChildDetails,
                    request_deserializer=auth__pb2.GetUserChildDetailsRequest.FromString,
                    response_serializer=auth__pb2.GetUserChildDetailsResponse.SerializeToString,
            ),
            'GetUserDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDetails,
                    request_deserializer=auth__pb2.GetUserDetailsRequest.FromString,
                    response_serializer=auth__pb2.GetUserDetailsResponse.SerializeToString,
            ),
            'GetUserPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserPermissions,
                    request_deserializer=auth__pb2.GetUserPermissionsRequest.FromString,
                    response_serializer=auth__pb2.GetUserPermissionsResponse.SerializeToString,
            ),
            'GetUserRole': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserRole,
                    request_deserializer=auth__pb2.GetUserRoleRequest.FromString,
                    response_serializer=auth__pb2.GetUserRoleResponse.SerializeToString,
            ),
            'GetServiceBoardUsersDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceBoardUsersDetails,
                    request_deserializer=auth__pb2.GetUsersDetailsRequest.FromString,
                    response_serializer=auth__pb2.GetServiceBoardUserDetailsResponse.SerializeToString,
            ),
            'GetPartnerApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartnerApiKey,
                    request_deserializer=auth__pb2.GetPartnerApiKeyRequest.FromString,
                    response_serializer=auth__pb2.GetPartnerApiKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """The authentication service definition.
    """

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateToken',
            auth__pb2.ValidateTokenRequest.SerializeToString,
            auth__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserChildHierarchy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserChildHierarchy',
            auth__pb2.GetUserChildHierarchyRequest.SerializeToString,
            auth__pb2.GetUserChildHierarchyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserChildDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserChildDetails',
            auth__pb2.GetUserChildDetailsRequest.SerializeToString,
            auth__pb2.GetUserChildDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserDetails',
            auth__pb2.GetUserDetailsRequest.SerializeToString,
            auth__pb2.GetUserDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserPermissions',
            auth__pb2.GetUserPermissionsRequest.SerializeToString,
            auth__pb2.GetUserPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserRole',
            auth__pb2.GetUserRoleRequest.SerializeToString,
            auth__pb2.GetUserRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceBoardUsersDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetServiceBoardUsersDetails',
            auth__pb2.GetUsersDetailsRequest.SerializeToString,
            auth__pb2.GetServiceBoardUserDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPartnerApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetPartnerApiKey',
            auth__pb2.GetPartnerApiKeyRequest.SerializeToString,
            auth__pb2.GetPartnerApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
