# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import telephony_pb2 as telephony__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telephony_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelephonyControlStub(object):
    """Bidirectional telephony control plane for Talko.
    Talko-service acts as gRPC CLIENT; the vendor telephony plane
    (OTOBA / console media gateway) serves these RPCs.
    Mirrors the existing REST semantics: POST /call, POST /call/hangup,
    POST /call/transfer — same fields, same outcomes.

    Unary call-control plane.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hangup = channel.unary_unary(
                '/telephony.TelephonyControl/Hangup',
                request_serializer=telephony__pb2.HangupRequest.SerializeToString,
                response_deserializer=telephony__pb2.HangupResponse.FromString,
                _registered_method=True)
        self.Transfer = channel.unary_unary(
                '/telephony.TelephonyControl/Transfer',
                request_serializer=telephony__pb2.TransferRequest.SerializeToString,
                response_deserializer=telephony__pb2.TransferResponse.FromString,
                _registered_method=True)
        self.Hold = channel.unary_unary(
                '/telephony.TelephonyControl/Hold',
                request_serializer=telephony__pb2.HoldRequest.SerializeToString,
                response_deserializer=telephony__pb2.HoldResponse.FromString,
                _registered_method=True)
        self.Mute = channel.unary_unary(
                '/telephony.TelephonyControl/Mute',
                request_serializer=telephony__pb2.MuteRequest.SerializeToString,
                response_deserializer=telephony__pb2.MuteResponse.FromString,
                _registered_method=True)
        self.GetCallStatus = channel.unary_unary(
                '/telephony.TelephonyControl/GetCallStatus',
                request_serializer=telephony__pb2.CallStatusRequest.SerializeToString,
                response_deserializer=telephony__pb2.CallStatusResponse.FromString,
                _registered_method=True)


class TelephonyControlServicer(object):
    """Bidirectional telephony control plane for Talko.
    Talko-service acts as gRPC CLIENT; the vendor telephony plane
    (OTOBA / console media gateway) serves these RPCs.
    Mirrors the existing REST semantics: POST /call, POST /call/hangup,
    POST /call/transfer — same fields, same outcomes.

    Unary call-control plane.
    """

    def Hangup(self, request, context):
        """Hang up an in-progress call (mirrors POST /call/hangup).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transfer(self, request, context):
        """Blind-transfer an in-progress call (mirrors POST /call/transfer).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hold(self, request, context):
        """Hold / unhold an in-progress call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mute(self, request, context):
        """Mute / unmute a leg of an in-progress call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCallStatus(self, request, context):
        """Poll signalling state for a call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelephonyControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hangup': grpc.unary_unary_rpc_method_handler(
                    servicer.Hangup,
                    request_deserializer=telephony__pb2.HangupRequest.FromString,
                    response_serializer=telephony__pb2.HangupResponse.SerializeToString,
            ),
            'Transfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Transfer,
                    request_deserializer=telephony__pb2.TransferRequest.FromString,
                    response_serializer=telephony__pb2.TransferResponse.SerializeToString,
            ),
            'Hold': grpc.unary_unary_rpc_method_handler(
                    servicer.Hold,
                    request_deserializer=telephony__pb2.HoldRequest.FromString,
                    response_serializer=telephony__pb2.HoldResponse.SerializeToString,
            ),
            'Mute': grpc.unary_unary_rpc_method_handler(
                    servicer.Mute,
                    request_deserializer=telephony__pb2.MuteRequest.FromString,
                    response_serializer=telephony__pb2.MuteResponse.SerializeToString,
            ),
            'GetCallStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCallStatus,
                    request_deserializer=telephony__pb2.CallStatusRequest.FromString,
                    response_serializer=telephony__pb2.CallStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telephony.TelephonyControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telephony.TelephonyControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelephonyControl(object):
    """Bidirectional telephony control plane for Talko.
    Talko-service acts as gRPC CLIENT; the vendor telephony plane
    (OTOBA / console media gateway) serves these RPCs.
    Mirrors the existing REST semantics: POST /call, POST /call/hangup,
    POST /call/transfer — same fields, same outcomes.

    Unary call-control plane.
    """

    @staticmethod
    def Hangup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telephony.TelephonyControl/Hangup',
            telephony__pb2.HangupRequest.SerializeToString,
            telephony__pb2.HangupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telephony.TelephonyControl/Transfer',
            telephony__pb2.TransferRequest.SerializeToString,
            telephony__pb2.TransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telephony.TelephonyControl/Hold',
            telephony__pb2.HoldRequest.SerializeToString,
            telephony__pb2.HoldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telephony.TelephonyControl/Mute',
            telephony__pb2.MuteRequest.SerializeToString,
            telephony__pb2.MuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCallStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/telephony.TelephonyControl/GetCallStatus',
            telephony__pb2.CallStatusRequest.SerializeToString,
            telephony__pb2.CallStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MediaPipeStub(object):
    """Bidirectional media pipe. Both sides stream raw audio frames;
    codec negotiated per stream (mulaw_8k matches Tata PSTN, pcm_48k
    matches LiveKit — see TalkoAudioBridge in pstn/services.py).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.stream_stream(
                '/telephony.MediaPipe/StreamAudio',
                request_serializer=telephony__pb2.AudioChunk.SerializeToString,
                response_deserializer=telephony__pb2.AudioChunk.FromString,
                _registered_method=True)


class MediaPipeServicer(object):
    """Bidirectional media pipe. Both sides stream raw audio frames;
    codec negotiated per stream (mulaw_8k matches Tata PSTN, pcm_48k
    matches LiveKit — see TalkoAudioBridge in pstn/services.py).
    """

    def StreamAudio(self, request_iterator, context):
        """Bidi audio: Talko streams uplink frames, gateway streams downlink.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaPipeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=telephony__pb2.AudioChunk.FromString,
                    response_serializer=telephony__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telephony.MediaPipe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('telephony.MediaPipe', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaPipe(object):
    """Bidirectional media pipe. Both sides stream raw audio frames;
    codec negotiated per stream (mulaw_8k matches Tata PSTN, pcm_48k
    matches LiveKit — see TalkoAudioBridge in pstn/services.py).
    """

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/telephony.MediaPipe/StreamAudio',
            telephony__pb2.AudioChunk.SerializeToString,
            telephony__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
