# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """User component service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPartnerUserDetailsByHierarchy = channel.unary_unary(
                '/user.UserService/GetPartnerUserDetailsByHierarchy',
                request_serializer=user__pb2.GetPartnerUserDetailsByHierarchyRequest.SerializeToString,
                response_deserializer=user__pb2.GetPartnerUserDetailsByHierarchyResponse.FromString,
                _registered_method=True)
        self.GetUsersAvailabilityStatus = channel.unary_unary(
                '/user.UserService/GetUsersAvailabilityStatus',
                request_serializer=user__pb2.GetUsersAvailabilityStatusRequest.SerializeToString,
                response_deserializer=user__pb2.GetUsersAvailabilityStatusResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """User component service
    """

    def GetPartnerUserDetailsByHierarchy(self, request, context):
        """RPC to get partner users details by hierarchy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersAvailabilityStatus(self, request, context):
        """RPC to get current_status for a list of user ids
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPartnerUserDetailsByHierarchy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartnerUserDetailsByHierarchy,
                    request_deserializer=user__pb2.GetPartnerUserDetailsByHierarchyRequest.FromString,
                    response_serializer=user__pb2.GetPartnerUserDetailsByHierarchyResponse.SerializeToString,
            ),
            'GetUsersAvailabilityStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersAvailabilityStatus,
                    request_deserializer=user__pb2.GetUsersAvailabilityStatusRequest.FromString,
                    response_serializer=user__pb2.GetUsersAvailabilityStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User component service
    """

    @staticmethod
    def GetPartnerUserDetailsByHierarchy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserService/GetPartnerUserDetailsByHierarchy',
            user__pb2.GetPartnerUserDetailsByHierarchyRequest.SerializeToString,
            user__pb2.GetPartnerUserDetailsByHierarchyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersAvailabilityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.UserService/GetUsersAvailabilityStatus',
            user__pb2.GetUsersAvailabilityStatusRequest.SerializeToString,
            user__pb2.GetUsersAvailabilityStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
