# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"H\n\nUserDetail\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"[\n\'GetPartnerUserDetailsByHierarchyRequest\x12\x12\n\npartner_id\x18\x01 \x01(\x03\x12\x1c\n\x14role_hierarchy_level\x18\x02 \x01(\x03\"S\n(GetPartnerUserDetailsByHierarchyResponse\x12\'\n\rusers_details\x18\x01 \x03(\x0b\x32\x10.user.UserDetail\"A\n\x16UserAvailabilityStatus\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x16\n\x0e\x63urrent_status\x18\x02 \x01(\t\"5\n!GetUsersAvailabilityStatusRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\x03\"e\n\"GetUsersAvailabilityStatusResponse\x12?\n\x19users_availability_status\x18\x01 \x03(\x0b\x32\x1c.user.UserAvailabilityStatus2\x82\x02\n\x0bUserService\x12\x81\x01\n GetPartnerUserDetailsByHierarchy\x12-.user.GetPartnerUserDetailsByHierarchyRequest\x1a..user.GetPartnerUserDetailsByHierarchyResponse\x12o\n\x1aGetUsersAvailabilityStatus\x12\'.user.GetUsersAvailabilityStatusRequest\x1a(.user.GetUsersAvailabilityStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDETAIL']._serialized_start=20
  _globals['_USERDETAIL']._serialized_end=92
  _globals['_GETPARTNERUSERDETAILSBYHIERARCHYREQUEST']._serialized_start=94
  _globals['_GETPARTNERUSERDETAILSBYHIERARCHYREQUEST']._serialized_end=185
  _globals['_GETPARTNERUSERDETAILSBYHIERARCHYRESPONSE']._serialized_start=187
  _globals['_GETPARTNERUSERDETAILSBYHIERARCHYRESPONSE']._serialized_end=270
  _globals['_USERAVAILABILITYSTATUS']._serialized_start=272
  _globals['_USERAVAILABILITYSTATUS']._serialized_end=337
  _globals['_GETUSERSAVAILABILITYSTATUSREQUEST']._serialized_start=339
  _globals['_GETUSERSAVAILABILITYSTATUSREQUEST']._serialized_end=392
  _globals['_GETUSERSAVAILABILITYSTATUSRESPONSE']._serialized_start=394
  _globals['_GETUSERSAVAILABILITYSTATUSRESPONSE']._serialized_end=495
  _globals['_USERSERVICE']._serialized_start=498
  _globals['_USERSERVICE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
