DID_CACHE_KEY = "pstn:did:{did_number}"
API_KEY_CACHE_KEY = "pstn:api_key:{partner_id}"
STREAM_CONTEXT_KEY = "stream_ctx:{stream_sid}"
PENDING_CALL_CONTEXT_KEY = "pending_call_ctx:{call_id}"

DID_CACHE_TTL_SECONDS = 300
API_KEY_CACHE_TTL_SECONDS = 60
STREAM_CONTEXT_TTL_SECONDS = 14400
PENDING_CALL_CONTEXT_TTL_SECONDS = 900

MAX_PENDING_MARKS = 8
ACK_WAIT_SECONDS = 2.0
CHUNK_SIZE = 160
